### ISSUE TITLE
Instance lookup

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#220]
Hi @kinmanli : two things on this page:  http://www.webarchive.org.uk/actdev/instances/list/?s=title&f=afed.org.uk

(i) could you confirm what the 'empty' link indicates ? (it produces a null pointer error at the minute)

(ii) in order to add a new instance from here,, what data needs to be input? A target URL, leading to a new instance record associated with that target ? If so, that isn't working at the minute.

Also @anjackson I guess that what needs to happen here is: user enters target URL, clicks Add Instance, and is given a list of dates of instances available in Wayback, one of which they select: "Create an Instance Record for this Instance That Exists Outside ACT" ?

**Comment by peterwebster** [comment]
I think part of this ticket is now superseded by #231 

I also now think that having an 'Add Instance' option in the target record really means 'Check in Wayback for Instances without matching records in ACT' @anjackson Useful when user wants to look for instances harvested since the last chron job.

The only remaining part is about the 'empty' link. What is this doing ? @kinmanli

**Comment by kinmanli** [comment]
Old "empty" url which was generated from old code and didn't handle multiple url for targets. This is now fixed

**Comment by peterwebster** [comment]
@kinmanli The 'empty' link still showing at http://www.webarchive.org.uk/actdev/instances/list/?s=title&f=afed.org.uk ?

**Comment by peterwebster** [comment]
@anjackson after discussion with @kinmanli , I'm now fairly sure that, in the target record view, user doesn't need to be able to add a new instance record - but does need to be able to trigger a check in the Wayback XML endpoint for any new instances for the target that have appeared since the last check (which is specified at #231 ) -  and for ACT to create new instance records for any such that it finds. (And alert the user that this has happened).

**Comment by peterwebster** [comment]
'Empty' link now removed - thanks @kinmanli 

Discussion on the other parts of this ticket now over at #231

**Comment by peterwebster** [comment]
@kinmanli  after discussion with @anjackson , we think we should comment out the Get New Instances in the target record. It shouldn't be necessary.

**Comment by kinmanli** [comment]
fixed

**Comment by peterwebster** [comment]
Thanks @kinmanli  - closing ticket now
