### ISSUE TITLE
Implement Collections feature

### ISSUE THREAD

**Issue by GilHoggarth** [ukwa/w3act#321]
From March 24 team meeting, Nicola asked when will the Collections feature be added into w3act. Talking to Kinman I understand that needs further clarification. Previously this has been discussed in #289 but is repeated here again as it's a different piece of development work.

> We also need this to update collections.

> Other API changes:
> * Collections key should not be quoted, i.e. "1" not "\"1\""
> * Collections API could include the full collections properties
> * Targets do not report collection_cats
> * The /api/targets/bycollection/X hook appears to be fully recursive. We need another hook that only reports Targets that are in exactly that category, not one of its children.
> * The instances are not available via the API (fix checked in)
> * Collection.updatedAt appears to be in milliseconds rather than the usual seconds since epoch.

And, questions from Kinman
>> * Targets do not report collection_cats

Do you mean the first level of the collection tree?

>> * The /api/targets/bycollection/X hook appears to be fully recursive. We need another hook that only reports Targets that are in exactly that category, not one of its children.

Do you need the recursive one with the children, as I can just ignore the 'children' field?

>> * Collection.updatedAt appears to be in milliseconds rather than the usual seconds since epoch.

It's a timestamp. What date format do you want it in?

**Comment by anjackson** [comment]
>> * Targets do not report collection_cats
>
> Do you mean the first level of the collection tree?

Good question. It's meant to mirror the value we can PUT/POST there, which I think means it should report ALL the categories in the collection tree.

>
>> * The /api/targets/bycollection/X hook appears to be fully recursive. We need another hook that only reports Targets that are in exactly that category, not one of its children.
>
> Do you need the recursive one with the children, as I can just ignore the 'children' field?

I don't quite understand that, but i think so yes. If I look at a top-level collection, I only want the targets that are in that collection, not one of it's sub-collections.

>
>> * Collection.updatedAt appears to be in milliseconds rather than the usual seconds since epoch.
>
> It's a timestamp. What date format do you want it in?

It's a timestamp at millisecond precision. I'd like it at seconds precision, i.e. ```seconds = (int)(milliseconds/1000)```

**Comment by kinmanli** [comment]
A "Target" now shows it's "collections/categories"

http://localhost:9000/actdev/api/targets/1/categories

```
[{"id":60,"name":"UK General Election 2015","createdAt":"Thu Feb 12 13:54:31 GMT 2015","updatedAt":1423749271,"publish":false},{"id":105,"name":"Election Blogs","createdAt":"Thu Feb 12 13:54:37 GMT 2015","updatedAt":1423749277,"publish":false,"parent":{"id":60,"name":"UK General Election 2015","createdAt":"Thu Feb 12 13:54:31 GMT 2015","updatedAt":1423749271,"publish":false}},{"id":284,"name":"UK response to Philippines disaster 2013","createdAt":"Thu Feb 12 13:54:44 GMT 2015","updatedAt":1423749284,"publish":true}]
```

A "Collection" now shows it's "Targets"

http://localhost:9000/actdev/api/collections/2/targets

```
[{"id":74,"url":"act-106","updatedAt":1426683582381,"title":"BBC News: Homepage","language":null,"revision":"initial revision","edit_url":"wct-19875","body":null,"nid":null,"vid":null,"is_new":null,"type":null,"status":null,"promote":null,"sticky":null,"created":null,"changed":null,"log":null,"comment":null,"comments":null,"comment_count":null,"comment_count_new":null,"feed_nid":null,"author":null,"fieldUrls":[{"id":18514,"url":"http://www.poopoo.co.uk","createdAt":null,"updatedAt":1426675997989,"domain":"poopoo.co.uk"},{"id":79,"url":"http://news.bbc.co.uk/","createdAt":null,"updatedAt":1423749289462,"domain":"news.bbc.co.uk"},{"id":78,"url":"http://www.bbc.co.uk/news/","createdAt":null,"updatedAt":1423749289461,"domain":"bbc.co.uk"}],"description":null,"active":true,"flagNotes":null,"value":null,"summary":null,"isTopLevelDomain":true,"isUkRegistration":false,"keywords":null,"synonyms":null,"dateOfPublication":null,"justification":null,"selectionType":"SELECTION","selectorNotes":null,"archivistNotes":null,"legacySiteId":null,"whiteList":null,"blackList":null,"licenseStatus":null,"tabStatus":null,"field_uk_domain":null,"field_uk_geoip":null,"field_crawl_permission":null,"field_url":null,"field_subject":null,"field_description":null,"field_uk_postal_address_url":null,"field_nominating_organisation":null,"field_suggested_collections":null,"field_collections":null,"field_crawl_start_date":null,"field_crawl_end_date":null,"field_license":null,"field_instances":null,"field_collection_categories":null,"field_qa_status":null,"field_snapshots":null,"field_notes":null,"formUrl":null,"dateOfPublicationText":null,"crawlStartDateText":"06-04-2013 13:00","crawlEndDateText":null,"crawlStartDateISO":"2013-04-06T13:00:00Z","crawlEndDateISO":null,"subjectSelect":null,"collectionSelect":null,"authorIdText":null,"fieldUrl":null,"field_urls":null,"field_subjects":null,"field_nominating_org":null,"field_collection_cats":null,"selector":null,"queued":false,"statusStr":"N/A","granted":false,"pending":false,"refused":false,"superseded":false,"notInitiated":false,"emailRejected":false,"field_special_dispensation":false,"field_special_dispensation_reaso":null,"field_uk_hosting":false,"field_live_site_status":null,"field_key_site":true,"field_wct_id":null,"field_spt_id":null,"field_uk_postal_address":false,"uk_postal_address_url":"http://belly.co.uk","field_via_correspondence":false,"field_professional_judgement":false,"field_professional_judgement_exp":null,"field_no_ld_criteria_met":false,"field_scope":"root","field_depth":"DEEP","field_ignore_robots_txt":false,"field_crawl_frequency":"DAILY"}]
```

Timestamp now in seconds

```
{... "updatedAt":1423749271, ....}
```

**Comment by kinmanli** [comment]
@anjackson to review the above prior to deployment to /actdev

**Comment by anjackson** [comment]
Looks good.

**Comment by GilHoggarth** [comment]
Waiting to be tested on /actdev.

**Comment by GilHoggarth** [comment]
Have checked https://www.webarchive.org.uk/act/api/targets/1/categories and https://www.webarchive.org.uk/act/api/targets/1/targets but not results, probably not understanding how this is used. 
Assigning to Roger to live testing.

**Comment by PsypherPunk** [comment]
According to the [routes](https://github.com/ukwa/w3act/blob/master/conf/routes) file, it looks like there's a mechanism for updating Collections:

    PUT /api/collections/:id controllers.CollectionController.collectionUpdate(id:Long)

...but not one for *creating* new ones (i.e. a `POST`).

**Comment by anjackson** [comment]
This should work now, I think

    curl -v -H "Content-Type: application/json" -X POST -d '{"name": "Test Collection"}' -u wa-sysadm@bl.uk:XXXX http://localhost:9000/act/api/collections

**Comment by PsypherPunk** [comment]
Confirmed this works on /actdev.

**Comment by nicolabingham** [comment]
@PsypherPunk @anjackson should we see the updated collection data from WCT in /actdev/ now? The collection taxonomies are still not up to date. There are also quite a few of the collections that are not listed at all in /actdev/. I have a list of the collections and targets we should be seeing in Excel, but can't attach that type of file here.

**Comment by anjackson** [comment]
Commit 9a4746aec19ea454ed55088323c4632842d4b251 removed the check for uniqueness on collection name.

**Comment by anjackson** [comment]
Issue of importing ACT collection data is an internal issue logged in TRAC as 2475. The functionality is now in place, I believe.
