### ISSUE TITLE
Granted licences assuming 'Invented Licence' type

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#453]
A number of licence requests sent from W3ACT as 'Open UKWA Licence (2014-)' licence type have been returned as Granted but have assumed the 'Invented Licence' type.

This has been happening since the last deployment of W3ACT.

@dorotawalker have any recent requests come back with the correct licence or are they all 'invented licence'?

These are the Target records that are affected:
1. https://www.webarchive.org.uk/act/targets/30367 Dorota Walker (@DorotaWalker) on Twitter 
2. https://www.webarchive.org.uk/act/targets/29652 Salisbury International Arts Festival 
3. https://www.webarchive.org.uk/act/targets/30369 fourteeneighteen 
4. https://www.webarchive.org.uk/act/targets/26993 Kirby Laing Institute For Christian Ethics, The
5. https://www.webarchive.org.uk/act/targets/42 Charles Rennie Mackintosh Society 
6. https://www.webarchive.org.uk/act/targets/3395 Muslim Association of Britain 
7. https://www.webarchive.org.uk/act/targets/30436 Thomas Forester Pottery 
8. https://www.webarchive.org.uk/act/targets/29342 Cairde na hEireann Liverpool 
9. https://www.webarchive.org.uk/act/targets/29616 Pop Up Festival 
10. https://www.webarchive.org.uk/act/targets/30470 Voices for the Library 
11. https://www.webarchive.org.uk/act/targets/30763 Woolf Institute 
12. https://www.webarchive.org.uk/act/targets/30739 Definition Audio Visual 
13. https://www.webarchive.org.uk/act/targets/30707 Old Royal Naval College 
14. https://www.webarchive.org.uk/act/targets/29741 Irish Easter Rising Centennial 
15. https://www.webarchive.org.uk/act/targets/43 Early Days of a Better Nation 
16. https://www.webarchive.org.uk/act/targets/30439 Great British Community, The 
17. https://www.webarchive.org.uk/act/targets/30809 WJM Transport - London, UK and European Transport 
18. https://www.webarchive.org.uk/act/targets/28398 UK Archives Discovery Network 
19. https://www.webarchive.org.uk/act/targets/30802 Lost Voice Guy (@LostVoiceGuy) on Twitter 
20. https://www.webarchive.org.uk/act/targets/30801 Lost Voice Guy 
21. https://www.webarchive.org.uk/act/targets/30819 NAM Aidsmap

**Comment by anjackson** [comment]
Ick, this should only happen for old ones. If it's happening for new ones that a bigger problem.

**Comment by anjackson** [comment]
Nil can you verify this locally/on your own dev version?

**Comment by dorotawalker** [comment]
I've counted and as of today we have two more invented licences (23 in total). Since reporting two more permissions were granted https://www.webarchive.org.uk/act/targets/30874 and https://www.webarchive.org.uk/act/targets/27271. I guess with every permission granted we get a new invented licence assigned. @nicolabingham do you want me to stop sending the permission requests until the bug is fixed?

**Comment by nicolabingham** [comment]
@anjackson what is the purpose of the invented licence? Is it a placeholder for additional licence templates we may want to issue, i.e. in addition to the standard Open UKWA licence?
@dorotawalker yes please stop sending licence requests in the short term.

**Comment by anjackson** [comment]
The invented license was only supposed to appear in development or testing, when there were no licenses in the system. It should not have appears in production.

**Comment by nicolabingham** [comment]
Thanks @anjackson. @dorotawalker yes, lets hang fire until the bug is resolved.

**Comment by dorotawalker** [comment]
For testing puroposes I've gone through the process of granting permission twice for the https://www.webarchive.org.uk/act/targets/30367. Now it has two licences (both invented).

**Comment by anjackson** [comment]
Okay, @niladreeb, I got to the bottom of this. Seems to be some kind of bug or edge-case in the EBean library we use to manage the DB mappings. The ```crawlPermission.license``` can sometimes be empty, but then a moment later be filled! So in some places the full object is fetched from the DB and in others it's not.  If I change the annotation, adding ```CascadeType.REFRESH```:

```diff
-       @ManyToOne
+       @ManyToOne(cascade = CascadeType.REFRESH)
        @JoinColumn(name="license_id")
     public License license;
```

it seems to start working again! I'm *amazed* by how flaky this seems to be. I can't really go through the whole codebase to add these, so we'll just have to keep an eye our for this kind of thing.

The next release could upgrade Play to a more recent version, along with the dependencies, so that might iron out bugs, it that's what the issue is.

**Comment by dorotawalker** [comment]
Tested on https://www.webarchive.org.uk/actstage/targets/30367#licensing, but still comes back as INVENTED LICENCE.

**Comment by anjackson** [comment]
Okay, I've made a further change that I think should address this.

**Comment by dorotawalker** [comment]
@anjackson I've gone through the process again for the same target, starting with 'Non Initiated' status and 'None' for the licence and unfortunately the INVENTED LICENCE was assigned again.

**Comment by anjackson** [comment]
Has Gil had a chance to deploy the fix? I only checked it into the source code repo - I didn't deploy it.

**Comment by dorotawalker** [comment]
Sorry, I've misunderstood. Probably he hasn't had a chance. I'll wait for @GilHoggarth to confirm and try again.

**Comment by GilHoggarth** [comment]
I'm guessing this fix is within the github repo code rather than in the git.wa wct-to-w3act repo? If so, i deployed the w3act v1.1.1, i.e., latest code as of Oct 28 - Wednesday morning.

Looks like I should redeploy again as Andy made a change last night, so doing so now.

**Comment by dorotawalker** [comment]
Still the same outcome. The INVENTED LICENCE is assigned to the target. I've checked both view and edit modes.

**Comment by niladreeb** [comment]
Working fine on actstage. Requesting @dorotawalker to check.

**Comment by dorotawalker** [comment]
Tested on the same target and it returned the Open UKWA Licence (2014-). All good then!

**Comment by GilHoggarth** [comment]
Dorota, please test this licence issue on /actstage

**Comment by dorotawalker** [comment]
Tested and works ok on actstage.

**Comment by dorotawalker** [comment]
Tested and working on act
