### ISSUE TITLE
Avoid searching for short/nonsense strings in URL lookup

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#473]
Having profiles memory usage on production, it seems the target-lookup functionality is sometimes searching for strings that will match a LOT of targets, e.g. 'http' or possible even ''. The search functionality should limit the results-set, and not search for silly/overly short strings.

**Comment by anjackson** [comment]
Sorry @ldbiz - I stole this one and had a go at it before noticing you were looking at it. Does it work okay for you? It's the search on the /act/targets/lookup page.

**Comment by anjackson** [comment]
Ah, just spoke to @niladreeb and I think we've each covered separate aspects, which is good. I fixed the AJAX auto-suggest search part only, but you're right, the normal search submission process needs this addressing too.

**Comment by GilHoggarth** [comment]
This seems to have introduced the problem not fixed it. On production /act entering 'http' doesn't trigger any lookup (at least no results show) but on /actstage suggestions are now listed.

As this isn't a showstopper, I'm pushing this to the next milestone.

**Comment by GilHoggarth** [comment]
Still on milestone 1.2.1 so @anjackson Andy to test on /act-ddhapt.

**Comment by anjackson** [comment]
Search is still somewhat slower that I'd like, but I can verify that short and common strings are no longer resulting in heavy queries.

**Comment by anjackson** [comment]
Looks okay on live.
